name: Feature Request
description: Feature requests must be submitted as Discussions
title: "[Feature Request]: "
labels: ["invalid"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Feature requests are not accepted as Issues.**

        Please submit your idea as a **Discussion** so it can be reviewed and refined collaboratively.

        👉 **Submit a Feature Request Discussion here:**
        https://github.com/OWNER/REPO/discussions/new?category=feature-requests
  - type: checkboxes
    attributes:
      label: Confirmation
      options:
        - label: I understand that feature requests belong in Discussions
          required: true
